apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-app-http-docker
  name: node-app-http-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-http-docker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-app-http-docker
    spec:
      nodeName: ubuntu-c38557
      containers:
      - image: kwe9kq6yc3md3qvk/node-app-http-docker:latest
        name: node-app-http-docker
        resources: {}
        volumeMounts:
        - mountPath: "/my-data"
          name: norlys-pv-storage
      - image: busybox
        name: busybox
        args:
        - sleep
        - "86400"
        resources: {}
        volumeMounts:
        - mountPath: "/my-data"
          name: norlys-pv-storage
        command: ["/bin/sh","-c"]
        args: ["while true; do date >> /my-data/date.txt; sleep 10; done"]
      volumes:
        - name: norlys-pv-storage
          persistentVolumeClaim:
            claimName: norlys-pv-claim
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: norlys-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: norlys-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/norlys/my-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu-c38557

