name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}"/node-app-http-docker:latest .
        working-directory: node-app-http-docker

      - name: Push Docker Image to Docker Hub
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}"/node-app-http-docker:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Authenticate and deploy to Kubernetes
        working-directory: k8s
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          kubectl config use-context kubernetes-admin@kubernetes \
            --kubeconfig=kubeconfig.yaml
          kubectl apply --kubeconfig=kubeconfig.yaml --namespace=default -f node-app-http-docker-k8s-deployment.yaml
