name: Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}"/node-app-http-docker:latest .
        working-directory: node-app-http-docker

      - name: Push Docker Image to Docker Hub
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}"/node-app-http-docker:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Authenticate and deploy to Kubernetes
        working-directory: k8s
        #env:
        #  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
        #  KUBE_NAMESPACE: default
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          kubectl config use-context kubernetes-admin@kubernetes \
            --kubeconfig=kubeconfig.yaml
          kubectl run testpod \
            --image "${{ secrets.DOCKERHUB_USERNAME }}"/node-app-http-docker:latest \
            --namespace default \
            --kubeconfig=kubeconfig.yaml

          #kubectl apply --kubeconfig=./kubeconfig.yaml --namespace=$KUBE_NAMESPACE -f nginx_deploy.yml
